apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodename-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodename
  template:
    metadata:
      labels:
        app: nodename
    spec:
      nodeName: k8s-worker1
      containers:
        - name: nginx
          image: nginx