apiVersion: v1
kind: LimitRange
metadata:
  name: lr
  namespace: lr-ns
spec:
  limits:
  - type: Container
    min:
      memory: 0.1G
    max:
      memory: 0.4G
    maxLimitRequestRatio:
      memory: 3
    defaultRequest:
      memory: 0.1G
    default:
      memory: 0.2G
