apiVersion: v1
kind: Pod
metadata:
  name: rq2-pod
  namespace: rq-ns
spec:
  containers:
  - name: container
    image: nginx
    resources:
      requests:
        memory: 0.5Gi
      limits:
        memory: 0.5Gi
