apiVersion: v1
kind: Secret
metadata:
  name: kd-sa-secret
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: admin-user
type: kubernetes.io/service-account-token